export const INIT = 'INIT';
export const USER_CHANGE_POKEMON = 'USER_CHANGE_POKEMON';
export const BOSS_CHANGE_POKEMON = 'BOSS_CHANGE_POKEMON';
export const USER_POKEMON_ATTACK = 'USER_POKEMON_ATTACK';
export const BOSS_POKEMON_ATTACK = 'BOSS_POKEMON_ATTACK';
export const HANDLE_DEAD_POKEMON = 'HANDLE_BOSS_DEAD_POKEMON';
export const HANDLE_END_GAME = 'HANDLE_END_GAME';
export const RUN_AWAY = 'RUN_AWAY';
